apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incident-desk
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: incident-desk-config
    literals:
      - WELCOME_MESSAGE=Welcome to your CKA Incident Desk
images:
  - name: incident-desk
    newName: docker.io/library/incident-desk
    newTag: bootstrap
