apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incident-desk-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: cka-local
  resources:
    requests:
      storage: 2Gi
